version: '3'

services:

  mysql:
    image: mysql:8.0.33
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: niikkos
      MYSQL_DATABASE: mysql
      MYSQL_USER: niikkos
      MYSQL_PASSWORD: niikkos
    ports:
      - "3306:3306"

  webserver:
    image: nginx:alpine
    working_dir: /var/www/html
#    volumes:
#      - .:/var/www/html:cached
    ports:
      - "80:80"

  php-fpm:
    build:
      context: etc/docker/php-fpm
    working_dir: /var/www/html
#    volumes:
#      - .:/var/www/html

volumes:
  db_data: {}