version: '3'

services:

  mysql:
    image: mysql:8.0.33
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: you
      MYSQL_DATABASE: playstation-collection-manager
      MYSQL_USER: you
      MYSQL_PASSWORD: you
    ports:
      - "3306:3306"

  webserver:
    image: nginx:alpine
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html:cached
      - ./etc/docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"

  php-fpm:
    build:
      context: etc/docker/php-fpm
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - ./etc/docker/php-fpm/php.ini:/etc/php/8.2/fpm/conf.d/50-setting.ini

volumes:
  db_data: {}